---
- name: Install and configure NGINX
  hosts: all
  become: yes

  pre_tasks:
    - name: Set SSH user for ubuntu systems
      set_fact:
        ansible_user: ubuntu
      when: ansible_os_family == "Debian"

    - name: Set SSH user for RedHat systems
      set_fact:
        ansible_user: ec2-user
      when: ansible_os_family == "RedHat"
  
  tasks:
    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install NGINX
      ansible.builtin.apt:
        name: nginx
        state: latest
      when: ansible_os_family == "Debian"

    - name: Create index.html
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content:  |
          <!DOCTYPE html>
          <html>
          <head><title>Server Details</title></head>
          <body>
          <h1>Served from {{ ansible_hostname }}</h1>
          </body>
          </html>
        mode: '0644'
    
    - name: Ensure NGINX is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes